package com.xworkz.collectionDTO.dto;

public enum Type {
	
	
	BOWANDARROW,SWORDS,SPEAR,DAGGER,PISTOL,RAPIER,REVOLVER,HALBERD,MACE,CLUB,CROSSBOW,BOLO,FLAMETHROWER,GRENADE,AX,LANDMINES,TANKS,MACHINEGUN,ROCKET,MISSILE;

}
